version: 2
jobs:
  build:
    working_directory: ~/kotlin-native-lambda-runtime
    docker:
      - image: c1phr/kotlin-native-lambda-runtime-compiler:latest
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "build.gradle" }}
      - run:
          name: Build runtime
          command: |
            ./gradlew clean build linuxTest
      - save_cache: # saves the project dependencies
          paths:
            - ~/.gradle
          key: deps-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/kotlin-native-lambda-runtime
    docker:
      - image: c1phr/kotlin-native-lambda-runtime-compiler:0.15
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Publish to Bintray
          command: ./gradlew generatePomFileForKotlinMultiplatformPublication generateMetadataFileForKotlinMultiplatformPublication bintrayUpload bintrayPublish -PbuildNum="${CIRCLE_TAG}"

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+[\-a-z]*$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^\d+\.\d+\.\d+[\-a-z]*$/