version: 2
jobs:
  build:
    working_directory: /kotlin-native-lambda-runtime
    docker:
      - image: c1phr/kotlin-native-lambda-runtime-compiler:latest
    steps:
      - checkout
      - run:
          name: Build runtime
          command: |
            ./gradlew clean build LambdaRuntimeTest
#      - deploy:
#          name: Publish to Bintray
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#              ./gradlew generatePomFileForLambdaRuntimePublication generateMetadataFileForLambdaRuntimePublication bintrayUpload bintrayPublish -PbuildNum="BUILD_${CIRCLE_BUILD_NUM}"
#            fi