version: 2
jobs:
  build:
    working_directory: /kotlin-native-lambda-runtime
    docker:
      - image: docker:18.06.1-ce
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/kotlin-native-lambda-runtime.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/kotlin-native-lambda-runtime.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=kotlin-native-lambda-runtime -t kotlin-native-lambda-runtime .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/kotlin-native-lambda-runtime.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/kotlin-native-lambda-runtime.tar
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Publish Docker Image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
              docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
              docker push $IMAGE_NAME:latest
              docker push $IMAGE_NAME:$IMAGE_TAG
            fi