version: 2
jobs:
  build:
    working_directory: /kotlin-native-lambda-runtime
    docker:
      - image: c1phr/kotlin-native-lambda-runtime:latest
    steps:
      - checkout
      - run:
          name: Build runtime
          command: |
            ./gradlew build
#      - deploy:
#          name: Publish Docker Image to Docker Hub
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#              ./gradlew bintrayPublish
#            fi